#! /bin/sh
set -e

LC_ALL=C
LANG=C
umask 022

ORIGINALSDIR="/usr/share/tzdata-au/original"
SUBDIRS="zoneinfo zoneinfo/posix zoneinfo/right"

mkdir -p -- "$ORIGINALSDIR"
for subdir in $SUBDIRS; do
    mkdir -p -- "$ORIGINALSDIR/$subdir/Australia"
    # Only archive files, not symlinks.
    # This ensures only files from the tzdata package are archived, and not
    # our replacement symlinks.
    find "/usr/share/$subdir/Australia" -type f -print0 | \
        xargs -0 --no-run-if-empty cp -flt "$ORIGINALSDIR/$subdir/Australia"
done

exit 0
# vim: ts=4 sw=4 et
